services:
  - type: web
    name: restaurante-api
    runtime: docker
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        value: mongodb+srv://2420192004:O3xMXCkmPtozU5xr@cluster0.a8axmqg.mongodb.net/restaurante?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: supersecreto_restaurante_arroz_freddy_2025
      - key: CLOUDINARY_CLOUD_NAME
        value: dgxphimei
      - key: CLOUDINARY_API_KEY
        value: 858135777845269
      - key: CLOUDINARY_API_SECRET
        value: xV8YCg8Qt61MDCKsiOVpp19hHDU
      - key: REDIS_HOST
        value: excited-owl-37640.upstash.io
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: AZMIAAIjcDFjMzViNTc3N2JiNzU0NTA5Yjg4MDE1ODQ2YTUzZTUyMXAxMA
      - key: REDIS_DB
        value: 0
      - key: METRICS_CACHE_TTL
        value: 300
      - key: REAL_TIME_CACHE_TTL
        value: 60
